"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Paintmap__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Paintmap__factory_1 = require("./Paintmap__factory");
Object.defineProperty(exports, "Paintmap__factory", { enumerable: true, get: function () { return Paintmap__factory_1.Paintmap__factory; } });
