/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Paintmap } from "./Paintmap";
export * as factories from "./factories";
export { Paintmap__factory } from "./factories/Paintmap__factory";
